name: 'Terraform Azure Destroy'

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-destroy:
    name: 'Terraform destroy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure Terraform Backend
        run:
          terraform init -backend-config="resource_group_name=VD_Storage" -backend-config="storage_account_name=taskboardstorageVD" -backend-config="container_name=taskboardcontainedVD" -backend-config="key=terraform.tfstate"

      - name: Terraform destroy
        run: terraform destroy -auto-approve
   
